spring:
  datasource:
    url: jdbc:mysql://10.7.46.119:3306/aka?useUnicode=true&characeterEncoding=utf-8&serverTimezone=UTC
    username: lsxsd
    password: lsxsd
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/**/*.xml